project:
  type: website
  output-dir: docs

website:
  title: "Henry Sywulak-Herr - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: Weekly Notes
        menu:
          - text: "Week 1"
            href: weekly-notes/week-01-notes.qmd
          - text: "Week 2"
            href: weekly-notes/week-02-notes.qmd
          - text: "Week 3"
            href: weekly-notes/week-03-notes.qmd
          - text: "Week 4"
            href: weekly-notes/week-04-notes.qmd
          - text: "Week 5"
            href: weekly-notes/week-05-notes.qmd
          - text: "Week 6"
            href: weekly-notes/week-06-notes.qmd
          - text: "Week 7"
            href: weekly-notes/week-07-notes.qmd
      - text: Labs
        menu:
          - href: labs/lab0/lab0_template.qmd
            text: "Lab 0"
      - text: Assignments
        menu:
          - href: assignments/assignment1/Sywulak-Herr_Henry_assignment1.qmd
            text: "Assignment 1: Census Data Exploration"
          - href: assignments/assignment2/Sywulak-Herr_Henry_assignment2.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
          - href: assignments/midterm/model_script.qmd
            text: "Midterm - Appendix"
          - href: assignments/midterm/model_presentation.qmd
            text: "Midterm - Presentation"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
